name: Intro to CI

on:
    push:    

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.4.0
              with:
                  version: 8
                  run_install: false

            - name: Install Dependencies
              run: pnpm install

            - name: Build
              run: pnpm run build
